### ISSUE TITLE
Avatar Seçimi ile görev listesi yönetimini uygulayarak öğrenelim.

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#1]
[filmAB Projesi - Süreç Yönetim Tablosu](https://github.com/orgs/IFL-Elestirmenler/projects/1) üzerinde TO DO (Yapılacaklar) kısmından konuyu IN PROGRESS (Üzerinde Çalışılıyor) kısmına alır mısınız?

**Comment by fahriyegulolur** [comment]
Sertaç Hocam, ben IN PROGRESS'e aldım.

**Comment by fahriyegulolur** [comment]
Biz Ali Batu'yla banner hazırlamıştık. Oradan avatar oluştururuz.



![Image](https://user-images.githubusercontent.com/109214557/180616638-0626da86-337a-4d8e-956f-6ac6bf23478a.jpg)

**Comment by sertacates** [comment]
Tamamdır, siz avatarı yaptığınızda tekrar konuşuruz. Buraya yazarsınız.

**Comment by allbattu** [comment]
Tamamdır hocam merak etmeyin iş bizdedir.

**Comment by fahriyegulolur** [comment]
Sertaç Hocam ben IN PROGRESS'e alıyorum. Ali Batu banner'ı sisteme yükler.

**Comment by allbattu** [comment]
Hocam biz Fahriye Gül ile avatarı oluşturduk, bu konuyu kapatıyorum ve bitirilenler kısmına atıyorum.
