### ISSUE TITLE
Saadin Oyucu - Mentör İle Tanışma

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#10]
Gençler, Mentör'ümüz (Saadin Oyuncu) belli oldu. Yarın uygun saatte izniniz olursa ben e-posta atıp bir randevu isterim, hem tanışma hem de projenin mevcut durumunu anlatma fırsatımız olur, uygun mudur?

**Comment by allbattu** [comment]
26 veya 27 Temmuz bana uygun değil geri kalan günler uygun hocam.

**Comment by fahriyegulolur** [comment]
Hocam bana da 26'sı uygun değil. Onun dışında uygunum.

**Comment by sertacates** [comment]
Yarın makul bir saatte e-posta atarım ve konuyu ÜZERİNDE ÇALIŞILANLAR (In Progress) alanına taşırım.

**Comment by sertacates** [comment]
e-Posta attım, sizleri de e-postanın bilgi kısmına ekledim, e-posta adreslerinize e-postanın bir kopyası gelmiştir. Konuyu ÜZERİNDE ÇALIŞILANLAR (In Progress) alanına taşıyorum, e-postalarımızı kontrol edelim. Randevu istediğimiz bilgisini ilettik, bize dönüt verdiğinde o tarih ve saatte hazır olalım. Buradan da iletirim.

**Comment by sertacates** [comment]
**Konu:** TeknoFest Doğal Dil İşleme Yarışması Serbest Başvuru Kategorisi Mentörümüz ile Tanışma ve Süreç Bilgilendirme / Değerlendirme Toplantısı
**Tarih:** 25 Temmuz 2022
**Saat:** 11:00 (Öğleden Önce) (GMT+3)

Zoom Toplantısına Katılım Bağlantısı, Toplantı Kimliği ve Parolayı özelden ilettim. Zamanında toplantıda olalım. Toplantı sonrasında konuşulan konular ve alınan kararlara göre YAPILACAKLAR LİSTESİ'ni (Todo) güncelleriz.

**Comment by fahriyegulolur** [comment]
Tamam hocam o saate hazır oluruz

**Comment by allbattu** [comment]
Tamam hocam o zaman orada oluruz

**Comment by sertacates** [comment]
Saadin Hocamızın önerdiği **https://towardsdatascience.com/the-4-recommendation-engines-that-can-predict-your-movie-tastes-109dc4e10c52** ve **https://github.com/merveyapnaz/Tavsiye-Sistemleri-Recommender-System** dokümanları inceledik. Türkçe üzerinde çalışmak ve film özetlerinden yararlanmak için Veri Kümesi ve Model Eğitimi ile ilgili başlıktan devam edelim. Bu başlığı kapatıyorum.
