### ISSUE TITLE
Repo Etiketleri ve Açıklamaların Güncellenmesi

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#11]
Gençler, repo etiketlerini ve açıklamaları https://www.acikhack.com/ adresini de takip ederek güncelleyelim mi?

**Comment by fahriyegulolur** [comment]
nlp, tddi, öneri, recommend ve yapay zeka diye etiket oluşturuyorum. Siteden güncel olarak takip ederiz.

**Comment by allbattu** [comment]
Verilen filmlere göre film önerisinde bulunan bir öneri robotudur.
Hocam ben şimdilik böyle yazdım sunuma doğru güncelleriz.

**Comment by sertacates** [comment]
Ali Batu, bu başlığı (issue) ÜZERİNDE ÇALIŞILANLAR (In Progress) alanında REDAME.md Dosyasını düzenleyelim girdisinin altına alır mısın? Takip edelim sunuya doğru başlığı kapatırız, olur mu?

**Comment by allbattu** [comment]
Olur hocam.
