### ISSUE TITLE
Özetten Film Arama

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#12]
Gençler, özetten film arama yapmak için Fahriye Gül, veri kümemizi Türkçeleştirdi. Saadin Hocamız ile görüşelim o da uygun görürse kullanıcı "uzayda kızıldereli ve kovboy savaşı" yazdığı zaman mevcut film özetlerimizin içinde bu isteğe en yakın 10 tanesini listeleyelim.

**Comment by sertacates** [comment]
Gençler, tartışma kısmına yazdıklarımıza göre bu kısmı da güncelleyelim. Yöntem burada da yazsın ve kodlarınızı sisteme yüklemeyi unutmayın.

**Comment by sertacates** [comment]
Özetten film arama nasıl gidiyor, https://github.com/IFL-Elestirmenler/FilmAB/blob/main/filmOzetindenBenzerFilmlerinBulunmasi.ipynb bu kısımda sanırım benzerliklerde biraz problem var, üzerine eğilelim. Bulduğunuz kaynaklar yerinde ve güzel Saadin hocamızın ilettiği içerikte arama kısmına bakabilirsiniz https://github.com/merveyapnaz/Tavsiye-Sistemleri-Recommender-System. 17 benzerlikten öklit seçmişsiniz ama galiba hala çalışmanız devam ediyor, bu yöntemleri karşılaştıralım, sanki Saadin hocamızın ilettiği kısımda cosin benzerliği kullanılmıştı. Onu da denemeyi unutmayın. Akşama kadar çıktılar hazır olursa iyi olur, bulunan 10 filmi benzerlik türüne göre karşılaştıralım.

**Comment by sertacates** [comment]
https://www.datacamp.com/tutorial/recommender-systems-python

**Comment by fahriyegulolur** [comment]
Özetten film arama dosyası bu [linkte](https://github.com/IFL-Elestirmenler/FilmAB/blob/main/filmOzetindenBenzerFilmlerinBulunmasi_ZEMBEREK.ipynb) hocam, bu konuyu bitirilenler kısmına alıyorum.
