### ISSUE TITLE
Verilen Film İsimlerinden Arama

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#13]
Gençler, verilen film isimlerinden arama yapmak için Fahriye Gül, veri kümemizi Türkçeleştirdi. Saadin Hocamız ile görüşelim o da uygun görürse kullanıcı bir kaç film ismi girsin o filmlerin özetlerinden anahtar kelimeler çıkartalım ve mevcut film özetlerimizin içinde bu anahtar kelimelere en yakın 10 tanesini listeleyelim.

**Comment by sertacates** [comment]
Gençler, tartışma kısmına yazdıklarımıza göre bu kısmı da güncelleyelim. Yöntem burada da yazsın ve kodlarınızı sisteme yüklemeyi unutmayın.

**Comment by sertacates** [comment]
Burada bir ilerlememiz var mı? @allbattu Ali Batu, bu kısma el atmak ister misin?

**Comment by sertacates** [comment]
https://www.datacamp.com/tutorial/recommender-systems-python

**Comment by fahriyegulolur** [comment]
Verilen film isimlerinden arama dosyası bu [linkte](https://github.com/IFL-Elestirmenler/FilmAB/blob/main/toplam10filmIsmindenOzetlerineBakipBenzerFilmlerinBulunmasi.ipynb) hocam, konuyu bitirilenler kısmına alıyorum.
