### ISSUE TITLE
Proje Gelişim Aşamaları

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#17]
Gençler, kodlarınızı yüklüyor değiştiriyorsunuz ama tek tek github üzerinden incelemek zaman alır, Proje Gelişim Aşaması diye bir README benzeri dosya oluşturalım, neyi neden yaptığımızı o kısımda veriler/bulgular ile izah edelim.

**Comment by sertacates** [comment]
Galiba proje gelişim aşamaları ile ilgili belge hazır değil, toplantıda bunu da konuşalım sonra neyi nereden buldunuz demesinler.

**Comment by fahriyegulolur** [comment]
Tamamladık hocam, bu konuyu bitirilenler kısmına alıyorum.
