### ISSUE TITLE
Sosyal Medya Görünümü - Logo, Etiketler ve Proje Açıklaması

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#2]
Gençler, isterseniz şimdiden https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview bu dokümanı okuyup sosyal medya için hazırladığınız banner'ı sisteme atarsanız sevinirim.

**Comment by fahriyegulolur** [comment]
Sertaç Hocam ben IN PROGRESS'e alıyorum. Ali Batu banner'ı sisteme yükler.

**Comment by sertacates** [comment]
Tamamdır, Ali Batu ile etiketleri de düzenleyip iş tamamlanınca konuyu (issue) tamamlananlar bölümüne (done) alıp konuyu (issue) kapatalım.

**Comment by allbattu** [comment]
Hocam biz fahriyeyle beraber bu konuyu hallettik. Bunu kapatıp bitirilenler kısmına alıyorum.

**Comment by sertacates** [comment]
Gençler, sosyal medya banner boyutu uygun değil, konuyu tekrar açıyorum ve  ÜZERİNDE ÇALIŞILANLAR (In Progress) alanına alıyorum. Fahriye Gül, uygun zamanda banner (sayfa tanıtım pankartına / afişine) bir el atalım.

**Comment by fahriyegulolur** [comment]
Tamam hocam, banner'ı tekrar düzenlerim.

**Comment by fahriyegulolur** [comment]
Hocamönceden banner'ı düzenlemiştim ama bu konuyu kapatmayı unutmuşuz. Konuyu bitirilenler kısmına atıyorum.
