### ISSUE TITLE
README.md Dosyasını düzenleyelim.

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#3]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax buradaki dokümanı inceleyerek README.md dosyasını düzenleyelim.

**Comment by fahriyegulolur** [comment]
Hocam in progress'e alıyorum. Ne koyalım?

**Comment by allbattu** [comment]
Hocam, Fahriye Gül, şimdilik sadece tanıtım yazalım daha projeyle ilgili kod eklemedik.

**Comment by sertacates** [comment]
Tamam, o zaman IN PROGRESS'te (Üzerinde Çalışılanlar) kısmında en üstte dursun. Her seferinde burada yazıp içeriğini güncelleriz. Son kapatılacak başlığımız bu olur ve proje bittiğinde bu başlığı da kapatırız. Olur mu?

**Comment by sertacates** [comment]
Ali Batu, senin README.md dosyasına yaptığın girdi gözükmüyor. Benim ve Fahriye Gül'ün yaptığı gibi girdi yaparsan sevinirim. Bir de sıralamayı değiştirirsen iyi olur. Sen en üstte, altta Fahriye Gül en altta da benim ismim yazsın, olur mu?



![Image](https://user-images.githubusercontent.com/34302399/180639363-c8acf856-3310-4859-8d36-063e06bd1e96.png)

**Comment by allbattu** [comment]
Tamam hocam hemen düzeltiyorum

**Comment by sertacates** [comment]
![Ekran görüntüsü 2022-07-31 130817](https://user-images.githubusercontent.com/34302399/182021334-ba6f5bf8-c542-40e5-9cdb-a9bb17c01d03.jpg)


@fahriyegulolur README dosyasının içeriği düzenlemişsin. Bu veri kümesinin bilgilerini eklemişsin. Teşekkür ederiz.

**Comment by fahriyegulolur** [comment]
Hocam proje tanıtımını da güncelledim.
