### ISSUE TITLE
Hugging Face üzerinden aldığınız kursu bitti mi?

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#4]
9 bölümlük https://huggingface.co/course/chapter0/1 kursunu tamamlayabildiniz mi? Neredesiniz?

**Comment by fahriyegulolur** [comment]
Hocam tamamladım ama ilk 4 bölümü tekrar etmem lazım.

**Comment by allbattu** [comment]
Benim durumum da aynı hocam, In Progress'e alıyorum, 24-25 Temmuz'a bitiririz

**Comment by sertacates** [comment]
25 Temmuzda bu konuya tekrar bakarız. Eksik kısımlar ile ilgili ben de biraz konu anlatırım. Anlaşıldığından emin olduğumuzda konuyu kapatırız. O halde şimdilik size 2 gün daha... Kolay gelsin.

**Comment by fahriyegulolur** [comment]
Sağolun hocam

**Comment by allbattu** [comment]
Sağolun hocam

**Comment by sertacates** [comment]
Son örneklerle / çalışmalarla bu konunun tamamlandığını düşünüyorum. Eksik hissettiğiniz bir alan olursa lütfen yazın. Şimdilik bu konuyu da kapatıyorum.
