### ISSUE TITLE
"Doğal Dil İşleme- İsmail Arı Yaz Okulu 2018" videolarında durum nedir?

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#5]
[Doğal Dil İşleme- İsmail Arı Yaz Okulu 2018](https://www.youtube.com/watch?v=CzIUICJXAjY&list=PLMGWwuh6-mEe57iOtf1uo5DgZB288l0CQ) Bu bağlantıdan "Doğal Dil İşleme- İsmail Arı Yaz Okulu 2018" başlığında toplanan 6 videoyu izleyelim. Sunumda ve projemizde ilgili kısımlara dikkat ederiz.

**Comment by allbattu** [comment]
Hocam 27 Temmuz'da bitirmiş oluruz.

**Comment by fahriyegulolur** [comment]
Ben de 27 Temmuz'a bitirmiş olurum, konuyu IN PROGRESS'e alıyorum.

**Comment by sertacates** [comment]
Sanırım videolar tamamlandı, bu konu başlığını da kapatıyorum. @fahriyegulolur @allbattu
