### ISSUE TITLE
Proje Ara Yüzünü tasarladık mı?

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#6]
Gençler, ara yüz için ne düşünüyorsunuz? https://docs.python.org/3/library/tkinter.html Tk Interface yani Tk ara yüz kütüphanesi ile bir şeyler yapalım mı?

**Comment by fahriyegulolur** [comment]
Hocam biz de Tk ara yüzü düşünüyorduk. Konuyu IN PROGRESS'e alıyorum.

**Comment by allbattu** [comment]
Hocam biz de aynı şeyi düşünüyorduk hocam 30 Temmuz'a arayüzü çıkarmış oluruz.

**Comment by sertacates** [comment]
Bugün bir toplantı yapıp ön çalışmayı görelim mi? @fahriyegulolur @allbattu

**Comment by fahriyegulolur** [comment]
Olur hocam

**Comment by sertacates** [comment]
Sertaç Ateş sizi planlanmış Zoom toplantısına davet ediyor.

Konu: TeknoFest Doğal Dil İşleme Yarışması Serbest Başvuru Kategorisi Toplantı 08
Saat: 30 Tem 2022 06:30 ÖS İstanbul

Zoom Toplantısına Katılın
https://us04web.zoom.us/j/71751420760?pwd=Oq_jUZXDrRXUO-jjnbXDCAbCSPYKnh.1

Toplantı Kimliği: 717 5142 0760
Parola: TDDI_08

Gençler, ara yüz ne durumda toplantısı yapalım.

**Comment by allbattu** [comment]
Hocam ben tkinter ile 3 tane pencere hazırladım

**Comment by sertacates** [comment]
Tamam, 6:30'daki toplantıda bakarız, konuşuruz. Eline sağlık. @allbattu

**Comment by sertacates** [comment]
![Ekran görüntüsü 2022-07-30 173954](https://user-images.githubusercontent.com/34302399/182021186-74c7b657-1f59-41e8-ac1b-2a2f8bc6387f.jpg)
![Ekran görüntüsü 2022-07-30 174421](https://user-images.githubusercontent.com/34302399/182021187-69c69acc-9283-4644-9936-88691af0f828.jpg)
![Ekran görüntüsü 2022-07-30 174627](https://user-images.githubusercontent.com/34302399/182021189-fda328f6-22cd-4b1d-96ec-be6e0674c9b5.jpg)
![Ekran görüntüsü 2022-07-30 175004](https://user-images.githubusercontent.com/34302399/182021190-b69e97a7-d8e2-410a-81ff-c94fe8ac8231.jpg)

Toplantıda aldığımız kararlar bu şekildeydi. Bu değişiklikleri de yaptıktan sonra TDDİ için hazır olmuş olacaktır diye düşünüyorum. Değişiklikleri yapınca yine bir toplanıp değerlendirme yapalım. @allbattu @fahriyegulolur

**Comment by sertacates** [comment]
Sertaç Ateş sizi planlanmış Zoom toplantısına davet ediyor.

Konu: TeknoFest Doğal Dil İşleme Yarışması Serbest Başvuru Kategorisi Toplantı 10
Saat: 6 Ağu 2022 02:00 ÖS İstanbul

Zoom Toplantısına Katılın
https://us04web.zoom.us/j/79194820210?pwd=Xv2hKdBqNC6_7k4d-x3zgSyCygmUSr.1

Toplantı Kimliği: 791 9482 0210
Parola: TDDI_NLP10


Ali Batu, bu bağlantıdan saat 14.00 gibi gelir misin? Fahriye ve bana şu ara yüzün son halini göster de TDDİ'yi ara yüze entegre etmeye başlayalım.

**Comment by sertacates** [comment]
Ara Yüzün son hali nasıl oldu? İlerlememiz var mı?

**Comment by fahriyegulolur** [comment]
Ali Batu son halini yükler hocam, konuyu kapatıyorum.
