### ISSUE TITLE
Proje Literatür Araştırması tamamlandı mı?

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#7]
NLP ile ilgili örnek öneri listesi (NLP Based Recommender System With or Without User Preferences) github üzerinden bulup inceleyelim demiştik. Bulduklarımızı bir araya getirip bir zoom toplantısı yapalım mı? Bu toplantının ana gündemi öneri robotları olsun mu? Konu ile ilgili iş ve işlemleri ortaya çıkaralım mı? Bu toplantıda artık görev bölümü yapıp konuya başlayalım mı?

**Comment by fahriyegulolur** [comment]
Hocam konu üzerinde çalışıyoruz. Yarın zoom üzerinden bir toplantı yapabiliriz.

**Comment by allbattu** [comment]
Hocam benimkiler de yarına tamamlanmış olur bu konuyu In Progress'e alıyorum.

**Comment by sertacates** [comment]
Saadin Hocamızın önerdiği https://towardsdatascience.com/the-4-recommendation-engines-that-can-predict-your-movie-tastes-109dc4e10c52 ve https://github.com/merveyapnaz/Tavsiye-Sistemleri-Recommender-System dokümanlarını da inceledik. Mevcut çalışmamızla bunları bütünleştirmek için Veri Kümesi ve Model Eğitimi başlığından devam edelim.

Literatür taraması ile ilgili yaptığımız çalışmaları da toparlayıp README.md kısmına ekleyelim. @fahriyegulolur @allbattu

**Comment by allbattu** [comment]
Hocam, çok makale okuduk parça parça kullandığımız kısmı kaynakça gibi belirtelim mi?

**Comment by sertacates** [comment]
Olur, iyi olur ama ara ara atmayı ihmal etmeyin, en sonunda APA formatında sıralayıp projeyi bitiririz.

**Comment by sertacates** [comment]
https://towardsdatascience.com/how-to-rank-text-content-by-semantic-similarity-4d2419a84c32 Buna bakan oldu mu? Ali Batu, Fahriye TF IDF yapıyor, sen TS-SS olayına hakim misin, bir el atar mısın? Bir de hala literatürü yazmamışsınız, zoomdaki konuştuğumuz kullandığımız literatürü buraya ve readme.md'ye ekleyelim.

**Comment by fahriyegulolur** [comment]
https://www.veribilimiokulu.com/natural-language-toolkitnltk/

**Comment by fahriyegulolur** [comment]
https://medium.com/kodcular/do%C4%9Fal-dil-i%CC%87%C5%9Fleme-nedir-uygulamal%C4%B1-%C3%B6rnek-b8eb15af7fd5

**Comment by fahriyegulolur** [comment]
https://monkeylearn.com/blog/what-is-tf-idf/

**Comment by fahriyegulolur** [comment]
https://medium.com/@cmukesh8688/tf-idf-vectorizer-scikit-learn-dbc0244a911a

**Comment by fahriyegulolur** [comment]
https://goodboychan.github.io/python/datacamp/natural_language_processing/2020/07/17/04-TF-IDF-and-similarity-scores.html

**Comment by fahriyegulolur** [comment]
https://leimao.github.io/blog/Cosine-Similarity-VS-Pearson-Correlation-Coefficient/

**Comment by fahriyegulolur** [comment]
https://towardsdatascience.com/17-types-of-similarity-and-dissimilarity-measures-used-in-data-science-3eb914d2681

**Comment by fahriyegulolur** [comment]
https://towardsdatascience.com/9-distance-measures-in-data-science-918109d069fa

**Comment by fahriyegulolur** [comment]
https://scikit-learn.org/stable/modules/metrics.html

**Comment by fahriyegulolur** [comment]
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances.html

**Comment by fahriyegulolur** [comment]
https://docs.scipy.org/doc/scipy/reference/spatial.distance.html

**Comment by sertacates** [comment]
https://ashutoshtripathi.com/2020/09/04/word2vec-and-semantic-similarity-using-spacy-nlp-spacy-series-part-7/

**Comment by sertacates** [comment]
https://scikit-learn.org/stable/modules/model_evaluation.html

**Comment by fahriyegulolur** [comment]
https://www.datacamp.com/tutorial/recommender-systems-python

**Comment by fahriyegulolur** [comment]
Hocam okuduğumuz ve kullandığımız makaleler [discussion] (https://github.com/IFL-Elestirmenler/FilmAB/discussions/21) kısmında . Kaynakçaya ekleyeceklerimizi burada belirtiriz.

**Comment by fahriyegulolur** [comment]
Sunuda detayları yazacağız hocam. Konuyu kapatıyorum, in progress'te kalsın.
