### ISSUE TITLE
Veri Kümesi ve Model Eğitimi ile ilgi çalışmamız hangi aşamada?

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#8]
IMDB ve Netflix filmler için veri kümesi paylaşıyor mu? 24 Temmuz 2022'de bir zoom toplantısı yapalım. Veri kümeleri, veri ön işlemleri ve model eğitimi konusunda konuşalım, olur mu?

**Comment by allbattu** [comment]
Hocam, 24 Temmuz 2022 Pazar günü toplantıda bu konuyu da ele alalım. https://www.imdb.com/interfaces/ ve https://flixable.com/ veya https://unogs.com/ adresinden Film Listelerini çıkarıp TAB veya COMA sperated value (tsv, csv) metin dosyasına çevireceğim, yarına yetişmiş olur. Pandas ve numpy ile veri kümesi üzerinde işlem yapabilir hale getiririm.

**Comment by fahriyegulolur** [comment]
Konuyu IN PROGRESS'e alıyorum. Yarın toplantıda konuşuruz.

**Comment by sertacates** [comment]
### **Veri Kümesi ile ilgili yapmamız gerekenler:**

**1.** Elimizde hangi veri var? ( Hangi alanlardan / sütunlardan oluşuyor, kaç adet kayıt / satır var, veri kaynağı neresidir? )
**2.** Elimizdeki veri kümesinde hangi veri ön işlemleri yapacağız (Veri temizleme {Gereksiz alanların silinmesi, verilerden fazla boşluk karakterlerinin silinmesi, anlamsız veya anlamlı bir farklılık oluşturmayacak noktalama işaretleri ile tarih/rakam silinmesi, belki anlamlı bir farklılık oluşturmayacaksa büyük küçük harf farkını kaldıralım, yine anlamlı bir farklılık oluşturmayacak kelimeleri kaldıralım (Stop Words)}, verileri anlamlı bir şekilde küçültelim (Tokenization),  Stemming ve Lemmatization yapalım yani bağlaçlardan kelimeleri arındıralım ve kökleri ortaya çıkartalım. )
**3.** https://www.nltk.org/ altında nltk araç setini ve https://spacy.io/ altında spaCy'yi inceleyelim.
**4.** Veri madenciliği yapalım. (CountVectorizer ve TF-IDF (Term Frequency — Inverse Document Frequency) ile ilgili ön çalışmamızı yapalım)
**5.** Veri Kümesi ön işlemlerinden sonra **Sınıflandırma ve Öneri Motoru** aşamasına geçebiliriz. 

**NOT:** Özellik çıkarma, eğitim ve tahmin için model arama / derin öğrenme kısmına odaklanacağız.

**Comment by allbattu** [comment]
Hocam IMDB ve Netflix'ten veri kümelerini çektim en kısa zamanda kayıt sayılarını belirteceğim.

**Comment by sertacates** [comment]
Tamamdır Ali Batu, Alan isimlerini de yazarsan seviniriz. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html bu dokümanı incelemeyi unutma.

**Comment by fahriyegulolur** [comment]
Hocam veri kümesi belli olsun nltk,spaCy,dilbaz ve zemberek kullanarak veri ön işlemlerini yapacağız

**Comment by allbattu** [comment]
Hocam, "CountVectorizer ve TF-IDF" bunların ne olduğuyla ilgili örnek gösterirseniz sevinirim

**Comment by sertacates** [comment]
Tamamdır, bir iki örnek hazırlayayım yarın bir ders yaparız.

**Comment by fahriyegulolur** [comment]
Hugging Face'ten Sınıflandırma ve Öneri Motoru ile ilgili örnek gösterebilir misiniz? Kursu bitirdik ama daha tam oturmadı.

**Comment by sertacates** [comment]
Tamamdır, onlarla ilgili de bir iki örnek hazırlayayım yarınki derste onları da hallederiz.

**Comment by sertacates** [comment]
Elimizdeki veri kümelerinin açıklamasını yavaş yavaş README.md dokümanına işleyelim. 

**Veri Kümesinin İsmi**
Alan İsmi 01: Açıklaması 01
Alan İsmi 01: Toplam NaN/Null ve veri işli satır sayısı
Alan İsmi 02: Açıklaması 02
Alan İsmi 02: Toplam NaN/Null ve veri işli satır sayısı
...
Alan İsmi n: Açıklaması n
Alan İsmi n: Toplam NaN/Null ve veri işli satır sayısı

**Comment by fahriyegulolur** [comment]
README.md dosyasını güncelledim hocam

**Comment by sertacates** [comment]
Açıkçası böyle bir tablo beklemiyordum, eline sağlık, çok güzel olmuş, seni biraz uğraştıracağız ama 
Satır Sayısı (Unknown)
Satır Sayısı (NaN)
Satır Sayısı (Dolu)
gibi üç bilgiyi daha o tabloya işlersen veri kümemizin kapsamını daha iyi anlarız.

**Comment by sertacates** [comment]
Bir de veri kümesinin plot kısmını Türkçeleştirelim. @fahriyegulolur

**Comment by sertacates** [comment]
Türkçeleştirmeyi yaptıktan sonra https://github.com/IFL-Elestirmenler/FilmAB/ github hesabına Proje Kapsamında Oluşturduğumuz Veri Kümeleri klasörü açıp csv dosyasını oraya ekleyelim. @fahriyegulolur

**Comment by fahriyegulolur** [comment]
> Açıkçası böyle bir tablo beklemiyordum, eline sağlık, çok güzel olmuş, seni biraz uğraştıracağız ama Satır Sayısı (Unknown) Satır Sayısı (NaN) Satır Sayısı (Dolu) gibi üç bilgiyi daha o tabloya işlersen veri kümemizin kapsamını daha iyi anlarız.

Tamamdır hocam, 3 sütun daha ekledim.

**Comment by fahriyegulolur** [comment]
> Bir de veri kümesinin plot kısmını Türkçeleştirelim. @fahriyegulolur

Tüm sütun başlıklarını ve satırların hepsini (Olay Dizisi, Yapıldığı Ülke, Türü) Türkçe yaptım hocam

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/182209416-fa2ce5f0-be5f-4f1f-b0a5-d0478f09dbd3.png)

Kontrol ettim, eline sağlık, bu veri kümesi işimizi görecektir. @fahriyegulolur

**Comment by sertacates** [comment]
Sentence similarity'e bakan oldu mu? Eldeki yöntemler arasındaki farkları karşılaştırdınız mı?

**Comment by sertacates** [comment]
Alanyazın'da (literatürde) paylaşmışsınız, şimdi gördüm. Çıktılarını karşılaştıralım, ana yöntemimiz belli olsun.

**Comment by fahriyegulolur** [comment]
Dosyaların hepsini yükledik hocam, konuyu kapatıyorum.
