### ISSUE TITLE
EĞİTİM: Numpy ve Pandas Kütüphanelerinde eksiğimiz var mı?

### ISSUE THREAD

**Issue by sertacates** [IFL-Elestirmenler/FilmAB#9]
Pandas ve Numpy ile ilgili eksiğimiz var mı?

**Comment by fahriyegulolur** [comment]
Konu üzerinde örnek çalışmalar yapıyoruz. Konu eksiğimiz yok.

**Comment by allbattu** [comment]
Hocam, https://www.w3schools.com/python/pandas/default.asp ve https://www.w3schools.com/python/numpy/default.asp den çalışmaya devam ediyoruz, konu eksiğimiz yok konuyu kapatıyorum.

**Comment by sertacates** [comment]
Tamamdır
